### ISSUE TITLE
[Question] How to send message to specific clients

### ISSUE THREAD

**Issue by AlexShniperson-INO** [touuki/netty-jsonrpc#6]
Hi

Thanks for sharing code.

I have a question: when WebSocket server receives some message i need to send them to some specific WebSocket clients, how can i do that with current architecture?

**Comment by AlexShniperson-INO** [comment]
look like i found answer: i just need to define `Channel` argument at `RPC` interface of needed method
```
interface ServerRpc {
    @JsonRpcMethod(value = "get.token", required = true)
    fun getToken(channel: Channel): String
}
```

now i have another question: is that possible to generalize `RPC` interface and define there some methods like below?
```
public interface RpcBase {
    void onConnected( Channel channel);

    void onDisconnected(Channel channel);

    void onError(Channel channel, Throwable cause);
}
```

**Comment by touuki** [comment]
> now i have another question: is that possible to generalize `RPC` interface and define there some methods like below?
> 
> ```
> public interface RpcBase {
>     void onConnected( Channel channel);
> 
>     void onDisconnected(Channel channel);
> 
>     void onError(Channel channel, Throwable cause);
> }
> ```

@AlexShniperson-INO For the `JSON-RPC` itself, it is a stateless protocol, so these methods should not be provided in this code. You can implement them in a higher-level code :)

**Comment by touuki** [comment]
@AlexShniperson-INO For example, you can extend the class `ChannelInboundHandlerAdapter` like following and use `pipeline.addLast` to implement.
```java
public class SubChannelInboundHandlerAdapter extends ChannelInboundHandlerAdapter {
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        //...
    }
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        //...
    }
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause)
            throws Exception {
        //...
    }
}
```

**Comment by AlexShniperson-INO** [comment]
ok thanks
